# Form implementation generated from reading ui file 'Project1GUI.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

#
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(487, 320)
        MainWindow.setMaximumSize(QtCore.QSize(5000, 5000))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.VotingBallot_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.VotingBallot_label.setGeometry(QtCore.QRect(95, 0, 300, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setUnderline(True)
        self.VotingBallot_label.setFont(font)
        self.VotingBallot_label.setObjectName("VotingBallot_label")
        self.ID_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.ID_label.setGeometry(QtCore.QRect(100, 60, 47, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.ID_label.setFont(font)
        self.ID_label.setObjectName("ID_label")
        self.ID_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ID_input.setGeometry(QtCore.QRect(150, 70, 191, 31))
        self.ID_input.setObjectName("ID_input")
        self.Canidates_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Canidates_label.setGeometry(QtCore.QRect(140, 100, 210, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setUnderline(True)
        self.Canidates_label.setFont(font)
        self.Canidates_label.setObjectName("Canidates_label")
        self.Jane_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.Jane_button.setGeometry(QtCore.QRect(30, 150, 115, 35))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.Jane_button.setFont(font)
        self.Jane_button.setObjectName("Jane_button")
        self.John_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.John_button.setGeometry(QtCore.QRect(180, 150, 125, 35))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.John_button.setFont(font)
        self.John_button.setObjectName("John_button")
        self.Submit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Submit_button.setGeometry(QtCore.QRect(180, 190, 113, 32))
        self.Submit_button.setObjectName("Submit_button")
        self.Feedback_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Feedback_label.setGeometry(QtCore.QRect(70, 210, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Feedback_label.setFont(font)
        self.Feedback_label.setText("")
        self.Feedback_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Feedback_label.setObjectName("Feedback_label")
        self.Bill_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.Bill_button.setGeometry(QtCore.QRect(320, 150, 115, 35))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.Bill_button.setFont(font)
        self.Bill_button.setObjectName("Bill_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 487, 43))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.VotingBallot_label.setText(_translate("MainWindow", "VOTING BALLOT"))
        self.ID_label.setText(_translate("MainWindow", "ID:"))
        self.Canidates_label.setText(_translate("MainWindow", "CANIDATES"))
        self.Jane_button.setText(_translate("MainWindow", "JANE"))
        self.John_button.setText(_translate("MainWindow", "JOHN"))
        self.Submit_button.setText(_translate("MainWindow", "SUBMIT"))
        self.Bill_button.setText(_translate("MainWindow", "BILL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())



